network:
  version: 2
  renderer: networkd
  ethernets:
    en:
      match: { name: "en*" }
      dhcp4: true
      dhcp6: false
      optional: true
    eth:
      match: { name: "eth*" }
      dhcp4: true
      dhcp6: false
      optional: true
